#
# accounts
#
 
test:
  login: test
  name: Test
  password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
  enable: true

demo:
  login: demo
  name: Demo
  password: a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
  enable: true