#
# configuration File (YAML syntax)
#

general:
  appURL: http://localhost/finder/      # URL Access. Can be either HTTP or HTTPS
  appTitle: My Virtual Desktop          # Application title
  version: 0.4.5
  dataPath: C:\xampp\www\_datas\
  thumbnailFolder: .thumbnails

theme:
  name: light-view
  path:
  
files:
  mimeMagicPath: C:\xampp\apache\conf\magic
  nameMaxLenght: 8                      # define the max lenght for the files and folders name
  hiddenItems:                          # list of files you don't want to be shown
    - .thumbnails
    - .DS_Store
    - Thumbs.db

  pictures:
    thumbFormats:
      -
        - 52
        - 52
      -
        - 800
        - 800
    type:
      - image/jpeg
      - image/png
      - image/gif
  
  video:
    type:
      - video/quicktime
      - video/x-msvideo
      - flv
      - video/mpeg

  audio:
    type:
      - audio/mpeg

# use for internal reasons
tmp:
