#
# configuration File (YAML syntax)
#

general:
  appURL: http://localhost/finder/      # URL Access
  appTitle: My Virtual Desktop          # Application title
  version: 0.4.4
  dataPath: C:/xampp/www/finder/datas/
  thumbnailFolder: .thumbnails

theme:
  name: light-view
  
files:
  nameMaxLenght: 8                      # define the max lenght for the files and folders name
  hiddenItems:                          # list of files you don't want to be shown
    - .thumbnails
    - .DS_Store
    - Thumbs.db
    - Picasa.ini

  pictures:
    thumbFormats:
      -
        - 52
        - 52
      -
        - 800
        - 800
    type:
      - image-jpeg
      - image-png
      - image-gif
      - image-jpg
  
  video:
    type:
      - avi
      - flv
      - mpg
      - mpeg

  audio:
    type:
      - mp3

# use for internal reasons
tmp:
